# Generated by blueprint from Blueprint.roc. Do not edit.
{
  description = "Development environments for full";

  inputs = {
    "nixpkgs".url = "github:NixOS/nixpkgs/nixos-unstable";
    "stable".url = "github:NixOS/nixpkgs/nixos-24.05";
    "roc".url = "github:roc-lang/roc-overlay";
    "utils".url = "github:numtide/flake-utils";
  };

  outputs = { self, ... }@inputs:
    let
      overlays = [ inputs."roc".overlays.default ];
      setsFor = system: {
        "nixpkgs" = import inputs."nixpkgs" { inherit system overlays; };
        "stable" = import inputs."stable" { inherit system overlays; };
      };
    in
    {
      devShells = {
        "x86_64-linux" = let sets = setsFor "x86_64-linux"; in {
          "default" = sets."nixpkgs".mkShell {
            packages = [
              sets."nixpkgs"."hello"
              sets."stable"."jq"
            ];
            "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n";
            "GREETING" = "hello";
          };
          "empty" = sets."nixpkgs".mkShell {
            packages = [
            ];
          };
        };
        "aarch64-linux" = let sets = setsFor "aarch64-linux"; in {
          "default" = sets."nixpkgs".mkShell {
            packages = [
              sets."nixpkgs"."hello"
              sets."stable"."jq"
            ];
            "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n";
            "GREETING" = "hello";
          };
          "empty" = sets."nixpkgs".mkShell {
            packages = [
            ];
          };
        };
        "riscv64-linux" = let sets = setsFor "riscv64-linux"; in {
          "default" = sets."nixpkgs".mkShell {
            packages = [
              sets."nixpkgs"."hello"
              sets."stable"."jq"
            ];
            "shellHook" = "echo \"hi \${USER}\"\nexport FOO=bar\n";
            "GREETING" = "hello";
          };
          "empty" = sets."nixpkgs".mkShell {
            packages = [
            ];
          };
        };
      };
      "blueprint" = { "version" = 1; };
    };
}
