# Generated by blueprint from Blueprint.roc. Do not edit.
{
  description = "Development environments for sample \"quoted\"";

  inputs = {
    "nixpkgs".url = "github:NixOS/nixpkgs/nixos-unstable";
    "roc".url = "github:roc-lang/roc-overlay";
  };

  outputs = { self, ... }@inputs:
    let
      overlays = [ inputs."roc".overlays.default ];
      setsFor = system: {
        "nixpkgs" = import inputs."nixpkgs" { inherit system overlays; };
      };
    in
    {
      devShells = {
        "x86_64-linux" = let sets = setsFor "x86_64-linux"; in {
          "default" = sets."nixpkgs".mkShell {
            packages = builtins.filter (sets."nixpkgs".lib.meta.availableOn sets."nixpkgs".stdenv.hostPlatform) [
              sets."nixpkgs"."git"
              sets."nixpkgs"."llvmPackages"."bintools"
            ];
          };
          "ci" = sets."nixpkgs".mkShell {
            packages = builtins.filter (sets."nixpkgs".lib.meta.availableOn sets."nixpkgs".stdenv.hostPlatform) [
              sets."nixpkgs"."git"
            ];
          };
        };
        "aarch64-darwin" = let sets = setsFor "aarch64-darwin"; in {
          "default" = sets."nixpkgs".mkShell {
            packages = builtins.filter (sets."nixpkgs".lib.meta.availableOn sets."nixpkgs".stdenv.hostPlatform) [
              sets."nixpkgs"."git"
              sets."nixpkgs"."llvmPackages"."bintools"
            ];
          };
          "ci" = sets."nixpkgs".mkShell {
            packages = builtins.filter (sets."nixpkgs".lib.meta.availableOn sets."nixpkgs".stdenv.hostPlatform) [
              sets."nixpkgs"."git"
            ];
          };
        };
      };
    };
}
