# Generated by blueprint from Blueprint.roc. Do not edit.
{
  description = "Development environments for sample \"quoted\"";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    overlay0.url = "github:roc-lang/roc-overlay";
  };

  outputs = { nixpkgs, ... }@inputs:
    let
      pkgsFor = system: import nixpkgs {
        inherit system;
        overlays = [ inputs.overlay0.overlays.default ];
      };
    in
    {
      devShells = {
        "x86_64-linux" = let pkgs = pkgsFor "x86_64-linux"; in {
          "default" = pkgs.mkShell {
            packages = [
              pkgs."git"
              pkgs."llvmPackages"."bintools"
            ];
          };
          "ci" = pkgs.mkShell {
            packages = [
              pkgs."git"
            ];
          };
        };
        "aarch64-darwin" = let pkgs = pkgsFor "aarch64-darwin"; in {
          "default" = pkgs.mkShell {
            packages = [
              pkgs."git"
              pkgs."llvmPackages"."bintools"
            ];
          };
          "ci" = pkgs.mkShell {
            packages = [
              pkgs."git"
            ];
          };
        };
      };
    };
}
