((format ((major 1) (minor 0)))
 (name "full")
 (requires ("raw"))
 (systems ("x86_64-linux" "aarch64-linux" "riscv64-linux"))
 (inputs (((name "stable") (url "github:NixOS/nixpkgs/nixos-24.05") (kind Packages))
          ((name "roc") (url "github:roc-lang/roc-overlay") (kind Overlay))
          ((name "utils") (url "github:numtide/flake-utils") (kind Flake))))
 (shells (((name "default") (packages (((source "nixpkgs") (path ("hello"))) ((source "stable") (path ("jq"))))))
          ((name "empty") (packages ()))))
 (tasks (((name "greet") (shell "default") (run ("hello")))))
 (raw (((backend "nix") (target "shell:default")
        (value (Attrs (((name "shellHook") (value (Str "echo \"hi ${USER}\"\nexport FOO=bar\n")))
                       ((name "GREETING") (value (Str "hello")))))))
       ((backend "nix") (target "flake")
        (value (Attrs (((name "blueprint") (value (Attrs (((name "version") (value (Int 1)))))))))))
       ((backend "guix") (target "whatever") (value (Int 0))))))
