import ir.Ir

## Renders the blueprint IR as a Nix flake with one dev shell per IR shell.
Flake :: [].{

	render : Ir -> Str
	render = |ir| {
		overlay_inputs = ir.overlays.map_with_index(|url, i| "    overlay${i.to_str()}.url = ${quote(url)};")
		overlay_refs = ir.overlays.map_with_index(|_, i| "inputs.overlay${i.to_str()}.overlays.default")
		systems = ir.systems.map(|system| render_system(Ir.system_str(system), ir.shells))

		lines([
			"# Generated by blueprint from Blueprint.roc. Do not edit.",
			"{",
			"  description = ${quote("Development environments for ${ir.name}")};",
			"",
			"  inputs = {",
			"    nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";",
		])
			.concat(lines(overlay_inputs))
			.concat(
				lines([
					"  };",
					"",
					"  outputs = { nixpkgs, ... }@inputs:",
					"    let",
					"      pkgsFor = system: import nixpkgs {",
					"        inherit system;",
					"        overlays = [ ${Str.join_with(overlay_refs, " ")} ];",
					"      };",
					"    in",
					"    {",
					"      devShells = {",
				]),
			)
			.concat(Str.join_with(systems, ""))
			.concat(lines(["      };", "    };", "}"]))
	}

	render_system : Str, List(Ir.Shell) -> Str
	render_system = |system, shells| {
		body = shells.map(
			|shell| {
				pkg_lines = shell.tools.map(|path| "              pkgs.${attr_path(path)}")
				lines(["          ${quote(shell.name)} = pkgs.mkShell {", "            packages = ["])
					.concat(lines(pkg_lines))
					.concat(lines(["            ];", "          };"]))
			},
		)
		lines(["        ${quote(system)} = let pkgs = pkgsFor ${quote(system)}; in {"])
			.concat(Str.join_with(body, ""))
			.concat(lines(["        };"]))
	}

	attr_path : List(Str) -> Str
	attr_path = |path| Str.join_with(path.map(quote), ".")

	lines : List(Str) -> Str
	lines = |items| items.fold("", |acc, line| acc.concat(line).concat("\n"))

	## A Nix string literal.
	quote : Str -> Str
	quote = |value| {
		escaped = value
			.replace_each("\\", "\\\\")
			.replace_each("\"", "\\\"")
			.replace_each("\${", "\\\${")
			.replace_each("\n", "\\n")
		"\"${escaped}\""
	}
}

import "tests/sample.golden.nix" as golden : Str

expect {
	ir = Ir.{
		version: 1,
		name: "sample \"quoted\"",
		systems: [X86_64Linux, Aarch64Darwin],
		overlays: ["github:roc-lang/roc-overlay"],
		shells: [
			{ name: "default", tools: [["git"], ["llvmPackages", "bintools"]] },
			{ name: "ci", tools: [["git"]] },
		],
	}
	Flake.render(ir) == golden
}
