import ir.Ir
import ir.Value
import Backend

## The Nix backend: renders the IR as `flake.nix`, one dev shell per IR shell
## per system, and drives `nix flake lock` / `nix develop`.
##
## # Inputs and package sets
##
## Every IR input becomes a flake input. If there is no input named
## `nixpkgs`, `github:NixOS/nixpkgs/nixos-unstable` is added as a `Packages`
## input. Each `Packages` input is imported once per system as a package set,
## `sets."<name>"`, and every `Overlay` input's `overlays.default` is applied
## to every package set (not only nixpkgs). `Flake` inputs are only declared;
## nothing references them. `mkShell` comes from `sets."nixpkgs"`, so
## `nixpkgs` must be a `Packages` input.
##
## A shell package `{ source, path }` renders as `sets."<source>"."a"."b"`;
## `source` must name a `Packages` input.
##
## # Raw
##
## `raw` entries with backend `"nix"` are rendered as Nix *data*, never as Nix
## code: strings are escaped, so a raw value cannot reference `pkgs` or
## `inputs`. Targets:
##
## - `shell:<name>`: an `Attrs` value whose attributes are added to that
##   shell's `mkShell` arguments, e.g. `shellHook` or environment variables.
## - `flake`: an `Attrs` value whose attributes are added to the flake's
##   `outputs` (only useful for plain data, e.g. a `templates` description).
##
## An attribute may be set once per target, and not over one the backend
## writes (`packages` in a shell, `devShells` in `flake`).
##
## # Extensions
##
## No extension kinds are supported yet: an IR with any extension is refused.
NixBackend :: [].{

	backend : Backend
	backend = Backend.{
		name: "nix",
		features: ["raw"],
		render: |ir| render(ir).map_ok(|contents| [{ path: "flake.nix", contents }]),
		lock_file: "flake.lock",
		lock: |dir| ["nix", "flake", "lock", "path:${dir}"],
		update: |dir| ["nix", "flake", "update", "--flake", "path:${dir}"],
		enter_shell: |dir, shell| ["nix", "develop", "path:${dir}#${shell}"],
		run_in_shell: |dir, shell, command| ["nix", "develop", "path:${dir}#${shell}", "-c"].concat(command),
	}

	default_nixpkgs : Str
	default_nixpkgs = "github:NixOS/nixpkgs/nixos-unstable"

	## Render the IR as the text of flake.nix.
	render : Ir -> Try(Str, Str)
	render = |ir| {
		if !ir.extensions.is_empty() {
			kinds = ir.extensions.map(|e| "'${e.kind}' (${e.name})")
			return Err("this blueprint does not support extensions yet; Blueprint.roc uses ${Str.join_with(kinds, ", ")}")
		}
		inputs = with_default_nixpkgs(ir.inputs)
		check_inputs(inputs)?
		raw = ir.raw.keep_if(|r| r.backend == "nix")
		shell_names = ir.shells.map(|s| s.name)
		var $shell_raw = []
		var $flake_raw = []
		for r in raw {
			if r.target == "flake" {
				$flake_raw = $flake_raw.concat(raw_attrs(r)?)
			} else if r.target.starts_with("shell:") {
				name = r.target.drop_prefix("shell:")
				if !shell_names.contains(name) {
					return Err("raw nix target \"${r.target}\" names no shell; Blueprint.roc defines: ${Str.join_with(shell_names, ", ")}")
				}
				$shell_raw = $shell_raw.concat(raw_attrs(r)?.map(|a| { shell: name, attr: a }))
			} else {
				return Err("unknown raw nix target \"${r.target}\"; expected \"flake\" or \"shell:<name>\"")
			}
		}
		check_attr_names("the raw flake outputs", $flake_raw.map(|a| a.name), ["devShells"])?
		package_sets = inputs.keep_if(|i| i.kind == Packages).map(|i| i.name)
		var $shells = []
		for shell in ir.shells {
			for p in shell.packages_ {
				if !package_sets.contains(p.source) {
					return Err("shell \"${shell.name}\" uses ${Str.join_with(p.path, ".")} from \"${p.source}\", which is not a package set; package sets: ${Str.join_with(package_sets, ", ")}")
				}
			}
			extra = $shell_raw.keep_if(|x| x.shell == shell.name).map(|x| x.attr)
			check_attr_names("the raw attributes of shell \"${shell.name}\"", extra.map(|a| a.name), ["packages"])?
			$shells = $shells.append(render_shell(shell, extra))
		}
		shells_text = Str.join_with($shells, "")
		systems = ir.systems.map(
			|system|
				lines(["        ${quote(system)} = let sets = setsFor ${quote(system)}; in {"])
					.concat(shells_text)
					.concat(lines(["        };"])),
		)
		input_lines = inputs.map(|i| "    ${quote(i.name)}.url = ${quote(i.url)};")
		overlays = inputs.keep_if(|i| i.kind == Overlay).map(|i| "inputs.${quote(i.name)}.overlays.default")
		set_lines = package_sets.map(|name| "        ${quote(name)} = import inputs.${quote(name)} { inherit system overlays; };")
		flake_lines = $flake_raw.map(|a| "      ${quote(a.name)} = ${value_to_nix(a.value)};")
		Ok(
			lines([
				"# Generated by blueprint from Blueprint.roc. Do not edit.",
				"{",
				"  description = ${quote("Development environments for ${ir.name}")};",
				"",
				"  inputs = {",
			])
				.concat(lines(input_lines))
				.concat(
					lines([
						"  };",
						"",
						"  outputs = { self, ... }@inputs:",
						"    let",
						"      overlays = [ ${Str.join_with(overlays, " ")} ];",
						"      setsFor = system: {",
					]),
				)
				.concat(lines(set_lines))
				.concat(lines(["      };", "    in", "    {", "      devShells = {"]))
				.concat(Str.join_with(systems, ""))
				.concat(lines(["      };"]))
				.concat(lines(flake_lines))
				.concat(lines(["    };", "}"])),
		)
	}

	with_default_nixpkgs : List(Ir.Input) -> List(Ir.Input)
	with_default_nixpkgs = |inputs|
		if inputs.any(|i| i.name == "nixpkgs")
			inputs
		else
			[{ name: "nixpkgs", url: default_nixpkgs, kind: Packages }].concat(inputs)

	check_inputs : List(Ir.Input) -> Try({}, Str)
	check_inputs = |inputs| {
		var $seen = []
		for i in inputs {
			if $seen.contains(i.name) {
				return Err("input \"${i.name}\" is declared twice")
			}
			$seen = $seen.append(i.name)
			if i.name == "nixpkgs" and i.kind != Packages {
				return Err("input \"nixpkgs\" must be a package set (kind Packages); the Nix backend takes mkShell from it")
			}
		}
		Ok({})
	}

	raw_attrs : Ir.Raw -> Try(List({ name : Str, value : Value }), Str)
	raw_attrs = |r|
		match r.value {
			Attrs(attrs) => Ok(attrs)
			_ => Err("raw nix value for \"${r.target}\" must be Attrs")
		}

	check_attr_names : Str, List(Str), List(Str) -> Try({}, Str)
	check_attr_names = |what, names, reserved| {
		var $seen = []
		for name in names {
			if reserved.contains(name) {
				return Err("${what} set \"${name}\", which the Nix backend writes itself")
			}
			if $seen.contains(name) {
				return Err("${what} set \"${name}\" more than once")
			}
			$seen = $seen.append(name)
		}
		Ok({})
	}

	render_shell : Ir.Shell, List({ name : Str, value : Value }) -> Str
	render_shell = |shell, extra| {
		pkg_lines = shell.packages_.map(|p| "              sets.${quote(p.source)}.${attr_path(p.path)}")
		extra_lines = extra.map(|a| "            ${quote(a.name)} = ${value_to_nix(a.value)};")
		lines(["          ${quote(shell.name)} = sets.\"nixpkgs\".mkShell {", "            packages = ["])
			.concat(lines(pkg_lines))
			.concat(lines(["            ];"]))
			.concat(lines(extra_lines))
			.concat(lines(["          };"]))
	}

	## A Value as a Nix expression (data only, on one line).
	value_to_nix : Value -> Str
	value_to_nix = |value|
		match value {
			Str(s) => quote(s)
			Int(n) => if n < 0 "(${n.to_str()})" else n.to_str()
			Bool(b) => if b "true" else "false"
			List([]) => "[ ]"
			List(items) => "[ ${Str.join_with(items.map(value_to_nix), " ")} ]"
			Attrs([]) => "{ }"
			Attrs(attrs) => "{ ${Str.join_with(attrs.map(|a| "${quote(a.name)} = ${value_to_nix(a.value)};"), " ")} }"
		}

	attr_path : List(Str) -> Str
	attr_path = |path| Str.join_with(path.map(quote), ".")

	lines : List(Str) -> Str
	lines = |items| items.fold("", |acc, line| acc.concat(line).concat("\n"))

	## A Nix string literal.
	quote : Str -> Str
	quote = |value| {
		escaped = value
			.replace_each("\\", "\\\\")
			.replace_each("\"", "\\\"")
			.replace_each("\${", "\\\${")
			.replace_each("\n", "\\n")
			.replace_each("\r", "\\r")
			.replace_each("\t", "\\t")
		"\"${escaped}\""
	}
}

import "tests/sample.golden.nix" as sample_golden : Str
import "tests/full.golden.nix" as full_golden : Str

TestIr : {
	name : Str,
	requires_ : List(Str),
	systems : List(Str),
	inputs : List(Ir.Input),
	shells : List(Ir.Shell),
	tasks : List(Ir.Task),
	extensions : List(Ir.Extension),
	raw : List(Ir.Raw),
}

none : TestIr
none = { name: "x", requires_: [], systems: [], inputs: [], shells: [], tasks: [], extensions: [], raw: [] }

mk : TestIr -> Ir
mk = |t| Ir.{
	format: Ir.current_format,
	name: t.name,
	requires_: t.requires_,
	systems: t.systems,
	inputs: t.inputs,
	shells: t.shells,
	tasks: t.tasks,
	extensions: t.extensions,
	raw: t.raw,
}

sample_ir : Ir
sample_ir = mk({
	..none,
	name: "sample \"quoted\"",
	systems: ["x86_64-linux", "aarch64-darwin"],
	inputs: [
		{ name: "nixpkgs", url: "github:NixOS/nixpkgs/nixos-unstable", kind: Packages },
		{ name: "roc", url: "github:roc-lang/roc-overlay", kind: Overlay },
	],
	shells: [
		{ name: "default", packages_: [{ source: "nixpkgs", path: ["git"] }, { source: "nixpkgs", path: ["llvmPackages", "bintools"] }] },
		{ name: "ci", packages_: [{ source: "nixpkgs", path: ["git"] }] },
	],
})

full_ir : Ir
full_ir = mk({
	..none,
	name: "full",
	requires_: ["raw"],
	systems: ["x86_64-linux", "aarch64-linux", "riscv64-linux"],
	inputs: [
		{ name: "stable", url: "github:NixOS/nixpkgs/nixos-24.05", kind: Packages },
		{ name: "roc", url: "github:roc-lang/roc-overlay", kind: Overlay },
		{ name: "utils", url: "github:numtide/flake-utils", kind: Flake },
	],
	shells: [
		{ name: "default", packages_: [{ source: "nixpkgs", path: ["hello"] }, { source: "stable", path: ["jq"] }] },
		{ name: "empty", packages_: [] },
	],
	tasks: [{ name: "greet", shell: "default", run: ["hello"] }],
	raw: [
		{
			backend: "nix",
			target: "shell:default",
			value: Value.Attrs([
				{ name: "shellHook", value: Value.Str("echo \"hi \${USER}\"\nexport FOO=bar\n") },
				{ name: "GREETING", value: Value.Str("hello") },
			]),
		},
		{ backend: "nix", target: "flake", value: Value.Attrs([{ name: "blueprint", value: Value.Attrs([{ name: "version", value: Value.Int(1) }]) }]) },
		{ backend: "guix", target: "whatever", value: Value.Int(0) },
	],
})

expect NixBackend.render(sample_ir) == Ok(sample_golden)
expect NixBackend.render(full_ir) == Ok(full_golden)

# Default nixpkgs is added when the IR declares none.
expect match NixBackend.render(mk({ ..none, systems: ["x86_64-linux"] })) {
	Ok(text) => text.contains("\"nixpkgs\".url = \"github:NixOS/nixpkgs/nixos-unstable\";")
	Err(_) => False
}

expect NixBackend.value_to_nix(Value.Str("a\"b\\c\${d}\n")) == "\"a\\\"b\\\\c\\\${d}\\n\""
expect NixBackend.value_to_nix(Value.Str("$x \$ {y}")) == "\"$x \$ {y}\""
expect NixBackend.value_to_nix(Value.Int(-3)) == "(-3)"
expect NixBackend.value_to_nix(Value.Bool(False)) == "false"
expect NixBackend.value_to_nix(Value.List([])) == "[ ]"
expect NixBackend.value_to_nix(Value.Attrs([])) == "{ }"
expect NixBackend.value_to_nix(Value.List([Value.Int(1), Value.Int(-2), Value.Attrs([{ name: "a b", value: Value.List([Value.Bool(True)]) }])])) == "[ 1 (-2) { \"a b\" = [ true ]; } ]"

expect match NixBackend.render(mk({ ..none, raw: [{ backend: "nix", target: "bogus", value: Value.Attrs([]) }] })) {
	Err(msg) => msg.contains("unknown raw nix target \"bogus\"")
	Ok(_) => False
}

expect match NixBackend.render(mk({ ..none, raw: [{ backend: "nix", target: "shell:nope", value: Value.Attrs([]) }] })) {
	Err(msg) => msg.contains("names no shell")
	Ok(_) => False
}

expect match NixBackend.render(mk({ ..none, shells: [{ name: "s", packages_: [] }], raw: [{ backend: "nix", target: "shell:s", value: Value.Attrs([{ name: "packages", value: Value.List([]) }]) }] })) {
	Err(msg) => msg.contains("set \"packages\"")
	Ok(_) => False
}

expect match NixBackend.render(mk({ ..none, shells: [{ name: "s", packages_: [] }], raw: [{ backend: "nix", target: "shell:s", value: Value.Str("x") }] })) {
	Err(msg) => msg.contains("must be Attrs")
	Ok(_) => False
}

# Raw for other backends is ignored.
expect NixBackend.render(mk({ ..none, raw: [{ backend: "guix", target: "bogus", value: Value.Int(1) }] })).is_ok()

expect match NixBackend.render(mk({ ..none, inputs: [{ name: "utils", url: "github:numtide/flake-utils", kind: Flake }], shells: [{ name: "s", packages_: [{ source: "utils", path: ["x"] }] }] })) {
	Err(msg) => msg == "shell \"s\" uses x from \"utils\", which is not a package set; package sets: nixpkgs"
	Ok(_) => False
}

expect match NixBackend.render(mk({ ..none, extensions: [{ kind: "service", name: "db", value: Value.Attrs([]) }] })) {
	Err(msg) => msg == "this blueprint does not support extensions yet; Blueprint.roc uses 'service' (db)"
	Ok(_) => False
}

expect match NixBackend.render(mk({ ..none, inputs: [{ name: "nixpkgs", url: "github:x/y", kind: Flake }] })) {
	Err(msg) => msg.contains("must be a package set")
	Ok(_) => False
}
